/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "log.h"


/* Header for class com_commax_devicemanager_devicesetting_JNIManager */

#ifndef _Included_com_commax_devicemanager_devicesetting_JNIManager
#define _Included_com_commax_devicemanager_devicesetting_JNIManager


#ifdef __cplusplus
extern "C" {
#endif


/*
 * Class:     com_commax_devicemanager_devicesetting_JNIManager
 * Method:    scanDevice
 * Signature:
 */
//패키지명에 언더바 들어가면 오류발생(unSatisfiedLinked)
JNIEXPORT void JNICALL Java_com_commax_devicemanager_devicesetting_JNIManager_scanDevice
        (JNIEnv *, jclass, jbyteArray statusRequest, jint length);

/*
 * Class:     com_commax_devicemanager_devicesetting_JNIManager
 * Method:    openPort3
 * Signature:
 */
JNIEXPORT jint JNICALL Java_com_commax_devicemanager_devicesetting_JNIManager_openPort3
        (JNIEnv *env, jclass obj);

/*
 * Class:     com_commax_devicemanager_devicesetting_JNIManager
 * Method:    openPort4
 * Signature:
 */
JNIEXPORT jint JNICALL Java_com_commax_devicemanager_devicesetting_JNIManager_openPort4
        (JNIEnv *env, jclass obj);
/*
 * Class:     com_commax_devicemanager_devicesetting_JNIManager
 * Method:    close
 * Signature:
 */
JNIEXPORT jint JNICALL Java_com_commax_devicemanager_devicesetting_JNIManager_close
        (JNIEnv *env, jclass obj);

#ifdef __cplusplus
}
#endif
#endif
